version: '3'

services:
  app:
    build: .docker/docker
    image: app
    depends_on:
      - mysql
      - redis
    volumes:
      - ./:/application:cached

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=app
    volumes:
      - ./storage/tmp/db:/var/lib/mysql:cached

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - .docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/application:cached
    depends_on:
      - app

  redis:
    image: redis
    ports:
      - "6379:6379"
